crawler:
  max_page_num: 1
  save_path: 'memes_en'
oss:
  access_key_id: 
  access_key_secret: 
  bucket_name: 
  region: 'cn-beijing'
translate:
  app_id: 
  app_secret: 
  output_path: 'chinese_memes'
  max_key_length: 100